### ISSUE TITLE
How to preserve long lines when running Matlab?

### ISSUE THREAD

**Issue by catch22** [catch22/octave-doctest#108]
Looking for an alternative to 5ed01dad7fc7c69a05f03b84b4900ca9ebc96f6f.

I understand that the command window width can be queried using `get(0, 'CommandWindowSize')`, but there doesn't seem to be a way to change it. I also tried to set the `COLUMNS` environment variable (before starting Matlab), but it does not appear to be used.

Moreover, the default width when running Matlab from the command line seems to be equal to the width of the terminal, so fixing all doctests to some default width (as we had discussed in #96) also does not seem to be a viable alternative.

Unless you guys have a better idea I'll mark this as "upstream-bug" and "will-not-fix".

**Comment by cbm755** [comment]
I found a gui option: "set matrix display width to eighty columns", which would probably be better than current terminal width.  Maybe its accessible via java?

**Comment by catch22** [comment]
I couldn't find programmatic access to this option (also am not sure if it
is used when Matlab is run from the command line). :-/
