### ISSUE TITLE
Conditionally skipping doctests

### ISSUE THREAD

**Issue by catch22** [catch22/octave-doctest#111]
I've once again run into the problem that I would like to skip some doctests based on some condition (in this case, whether we are running on the travis-ci infrastructure, where certain packages cannot be installed; previously it was Octave vs. MATLAB). I wonder what's the best way to go about this (ping @cbm755  @oheim). Something like `+SKIPIF(variable)` or `+SKIP_IF_<VARIABLE>` (the latter being a bit more magic than I usually like ;))?

**Comment by oheim** [comment]
When this is just for the travis-ci you could create a different Make target for checking, which doesn't run the full set of tests.

How do the tests look like, which can't be run on Travis?

**Comment by catch22** [comment]
I have mentioned this in my previous post, but here are a couple of use cases: (1) Octave vs Matlab, (2) optional dependencies (e.g., various optimization backends that might or might not be installed), (3) really slow-running doctests that we do not want to run by default.

Using different make targets is indeed my current workaround, but it has two critical downsides: (1) It does not scale, i.e., the number of make targets required scales with the number of different configurations. (2) The information is stored in the wrong place. This goes opposite to the goals of doctest; in practice, it leads to a maintainance burden and it does not allow the desired level of granularity. This is why I would like to find a more appropriate solution.

My proposed solution is to provide a means to mark tests by one or several flags, and to run the test only if said flags are set. (This is kind of a standard pattern with unit testing packages.)
There could be a number of default flags (e.g., `MATLAB` and `OCTAVE`). For custom flags, we could either simply fall back to global variables (e.g., `+ENABLE_IF_FOO_BAR_BAZ` is enabled if the global variable `FOO_BAR_BAZ` is set) or have an API for setting those. Both have advantages and disadvantages and I do not yet have a strong sense of what should be preferred.

**Comment by catch22** [comment]
Please see PR #112 for a suggestion (let's discuss the specifics of it in the PR). @cbm755 @oheim

**Comment by catch22** [comment]
Fixed in 586bc40324f5b8b407673436dcd42644c3cb9e4a.
