### ISSUE TITLE
Skip code blocks w/o output by default

### ISSUE THREAD

**Issue by oheim** [catch22/octave-doctest#113]
There was a fruitful discussion in the Octave IRC yesterday. The particular problem that we tried to solve is that there are many `@example` blocks in the current Octave documentation, which can't/shouldn't be doc-tested.

For example:
* In `libinterp/corefcn/mappers.cc` approx. 50% of `@example` blocks contain mathematical definitions of functions or ascii art formulas.
* … also in the image package: [houghtf.m](http://hg.code.sf.net/p/octave/image/file/554d9840e69f/inst/houghtf.m#l29)
* The image package also has example blocks for the call syntax of particular functions without output [medfilt2.m](http://hg.code.sf.net/p/octave/image/file/554d9840e69f/inst/medfilt2.m#l28)

All of these cases would be solved, if doctest would ignore example blocks without output lines. Is there already an option to enable this behaviour? If not, I'd recommend that blocks without output lines shall be ignored unless a particular option is enabled, e.g., `+EXECUTE_EXAMPLES_WITHOUT_OUTPUT`.

Opinions?

**Comment by catch22** [comment]
Is this about texinfo-formatted tests only?

**Comment by cbm755** [comment]
My first reaction was a preference for off-by-default: i.e., easy enough for an Octave makefile to pass  `-EXECUTE_EXAMPLES_WITHOUT_OUTPUT`...

But maybe default could be on-by-default for texinfo and off-by-default for raw m-files.

@oheim: if one wants to *test* that something produces no output, do you think best practice is the following?
````
@example
  foo (x)
  @output{}
@end example
````
(which would still get tested under this proposal).  If that is the Right Thing to do, then I'm ok with this proposal.

(I suspect @catch22 and I agree this should not be the default for non-texinfo.)

**Comment by catch22** [comment]
@cbm755 "If that is the Right Thing to do, then I'm ok with this proposal." <- Same here.

**Comment by cbm755** [comment]
@oheim #119 does part of this.  Its not the default behaviour---I'm not sure we have consensus on that yet: see my comment above on how one should explicitly indicate for "no output" in Texinfo.

But it should work with `doctest . -recursive +SKIP_BLOCKS_WO_OUTPUT` (which would be fine for a Makefile, if a bit cumbersome for manual usage).

I figure we can either:
  * merge this as is for 0.4.1 and possibly change default behaviour for 0.5.0.
  * or defer this until after 0.4.1: especially if `SKIP_BLOCKS_WO_OUTPUT` seems like the wrong term.

**Comment by catch22** [comment]
For Texinfo I'll defer to your expertise. I think we should not add an option, though - let's just be  opinionated about it :-) (cf. my latest comment in #95 for a better reason)

For non-texinfo I wouldn't want this.

**Comment by catch22** [comment]
I think #147 settled this issue, right? (By enabling `TEXINFO_SKIP_BLOCKS_WO_OUTPUT` by default.)

**Comment by cbm755** [comment]
Oh yeah, thanks
