### ISSUE TITLE
presence of `foo` directory prevents doctest of `@foo` class

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#120]
I just tried making a `test/test_shadow/` and it *does* block testing of the class `test/@test_shadow` (tested only in Octave).  Octave seems to ignore (?) the `test_shadow` dir, e.g., doing `A = test_shadow(1)` makes a new object of class `@test_shadow`.

- [x] test interpreter behaviour in Octave
- [x] test interpreter in Matlab
- [x] I assume we should try to follow the interpreter behaviour as much as possible.
- [x] check/refactor the `doctest_collect` code, especially on Octave: we strip `@` then add it back later when traversing directories... (?)

**Comment by catch22** [comment]
Is this related to #88?

**Comment by cbm755** [comment]
Yes!  I left some comments in #88.
