### ISSUE TITLE
Are class methods testable on Windows OS?

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#123]
We have the following code:
````
    if is_octave()
      target.name = sprintf('@%s/%s', what, meths{i});
      target.link = '';
    else
````
i.e., `help @class/method`.  Is this correct on the Windows OS?  Or does it need to be `help @class\method`?  Can someone confirm that they have run doctest on Windows?

If it doesn't work on Windows, then may need to use `filesep()`.

**Comment by oheim** [comment]
The `help` function accepts both variants under Windows. You have to use filesep to make other functions work. I would use filesep to be on the save side.

I have quickly tested doctest under Windows. Collection works for class methods, but texinfo parsing fails. [This regexp](https://github.com/catch22/octave-doctest/blob/master/inst/private/doctest_collect.m#L279) fails to match `$` with Windows line endings.

**Comment by cbm755** [comment]
Thanks!

I might be off-base, but maybe when we put additional newlines into the text, we should be using `sprintf('\n')`---expands to `\n\r` or whatever on Windows?

E.g., I seem to rememer using code like  `newl = sprintf('\n')` and then `[newl 'foo' newl]` in Symbolic...

**Comment by oheim** [comment]
`sprintf ('\n')` doesn't convert the eol character. It just returns 1 byte `\n` on Windows.

I believe it would be easiest to normalize the input and convert all eol characters to `\n`. The regular expressions already are complicated enough. There are two places where we have to do this:
1. `get_help_text` retains the original file content. If the file has been developed under Windows with `\r\n` eol characters, we should replace these before doing further parsing.
2. `__makeinfo_` returns eol characters depending on the OS you run Octave on. If we are on Windows, we should replace `\r\n` eol characters.

The `$` not matching Windows eol characters probably is a bug inside regexp(rep). However, above normalization should be a decent workaround. If you agree I can develop a PR to make the extraction work on Windows.

**Comment by cbm755** [comment]
That would be great.  Especially as I do not have easy access to Windows at my current work so this would be hard for me.

Did you also test if doctest-0.4.0 worked on Windows?  If it used to work, I think this blocks 0.4.1.

**Comment by oheim** [comment]
I guess this is a regression which has been introduced together with the texinfo conversion via makeinfo. However, there might have been errors with windows line endings before. Should I check this with the old 0.4.0 release?

Please check whether the PR breaks something in Matlab.

**Comment by cbm755** [comment]
> Should I check this with the old 0.4.0 release?

Maybe, if it was broken and now fixed, we could put it in the NEWS file.

**Comment by oheim** [comment]
@cbm755, you are right. It was broken in 0.4.0. I have put in in the NEWS file and merged everything into master.
