### ISSUE TITLE
Last computed result `ans` gets lost between examples

### ISSUE THREAD

**Issue by oheim** [catch22/octave-doctest#126]
Due to the new `eval`s inside the for-loop which calls `evalc` on the tests, the last computed value `ans` gets lost between computations. The following example does not work anymore.

````
@example
>> 4
ans = 4
@end example

@example
>> ans
ans = 4
@end example
````

I believe that `evalin` instead of `eval` is no solution here. We probably are going to need two loops: One with the `eval`s to evaluate the xfail and skip conditions and a second one to `evalc` the test code.

Edit: This also depends whether the skip and xfail conditions may be stateful or must be stateless. A workaround solution would be to save the last `ans` value in a variable.

**Comment by oheim** [comment]
Probably the easiest solution is to use `eval ('x = y;');` instead of `x = eval ('y');`

**Comment by cbm755** [comment]
Thanks for this!  I rely on that quite a lot, but apparently only for named variables.

@catch22 more likely to have an opinion on the stateful/statelessness of skip/xfail conditions.

**Comment by oheim** [comment]
I have filed a bug report for Octave: [#46397](https://savannah.gnu.org/bugs/index.php?46397). Matlab should not be affected.

**Comment by oheim** [comment]
I have directly pushed a simple fix. If there are no problems with this in Matlab, please close the issue.
