### ISSUE TITLE
Directives should only be specified inline

### ISSUE THREAD

**Issue by catch22** [catch22/octave-doctest#127]
I was thinking that perhaps we should not allow to pass directives as part of the `doctest` call. Instead, all directives should be specified inline (as comments in the actual doctests). My rationale is that doctests should be self-documenting and self-contained: it should always be possible to call `doctest <function>`. 

Let me know what you think; I'm happy to provide a PR.

**Comment by cbm755** [comment]
A much weaker position would be allow it but stop advertising it at the top of `doctest.m`'s help text: I'd be ok with that for 0.4.x.

**Comment by catch22** [comment]
Sounds good! Do you have any thoughts on eventually phasing out that capability?

**Comment by cbm755** [comment]
Have not really thought about it yet.  As a general rule, fewer knobs is good: add them once [support them forever](https://xkcd.com/1172/).

But to add a data point: I think Python doctest does allow specifying directives globally.  No idea how much this is used in practice.

**Comment by cbm755** [comment]
While we're thinking about this project again, should we at least take the "weaker position" [mentioned above](https://github.com/catch22/octave-doctest/issues/127#issuecomment-156020303)?

**Comment by catch22** [comment]
Just out of curiosity - have you ever found a use case for this functionality?

**Comment by cbm755** [comment]
No, not in practice.

I guess theoretically the WHITESPACE one could be used in this way: I figured projects might have project-wide preferences about these things...  I

**Comment by catch22** [comment]
That's true. I feel that it is desirable that `doctest <target>` always works -- possibly after some setup script has been run that configures paths etc. One might also want to run doctests for targets in different projects, so this seems to preclude any solution that modifies the default directives by setting some global variables.

I think doctest could load the closest `.doctestrc` file in the target's directory or one of its parent directories before running doctests. I can't think of a major downside (it should be reasonably fast since it will only be done once for invocations like `doctest .`), but am not so inclined to implement it without a user/use case.

How about we (1) deprecate and subsequently remove support for specifying directives at the command level in the next major version, and (2) accept patches for adding project-global support for modifying directives (using e.g. a `.doctestrc` file).
