### ISSUE TITLE
Problem while installing on ubuntu (from forge)

### ISSUE THREAD

**Issue by genuinelucifer** [catch22/octave-doctest#133]
I am running octave 3.8.1 on Ubuntu 14.10 x64
When I issue ```pkg install -forge doctest``` I am getting the following error:
```
octave:9> pkg install -forge doctest
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.9/include/stdint.h:9:0,
                 from /usr/include/octave-3.8.1/octave/oct-conf-post.h:167,
                 from /usr/include/octave-3.8.1/octave/config.h:3357,
                 from /usr/include/octave-3.8.1/octave/../octave/oct.h:31,
                 from doctest_evalc.cc:18:
/usr/include/stdint.h:31:53: error: no include path in which to search for stdint.h
 #if __STDC_HOSTED__ && __has_include_next(<stdint.h>)
                                                     ^
/usr/include/stdint.h:31: confused by earlier errors, bailing out
g++: error: doctest_evalc.o: No such file or directory
For information about changes from previous versions of the doctest package, run 'news doctest'.
```
.
I searched online and saw many other softwares have the same problem with stdint.h but there was no general solution to this. Any suggestions on how to try and fix this?

**Comment by cbm755** [comment]
Does installing `liboctave-dev` or whatever the devel package for octave is called fix this?

@catch22 its not good that the package apparently none-the-less installs (`For information about changes`...).  Makefile problem?

**Comment by cbm755** [comment]
@genuinelucifer see also #65.

**Comment by catch22** [comment]
Perhaps @oheim can advise on the `Makefile` question?

**Comment by genuinelucifer** [comment]
> Does installing liboctave-dev or whatever the devel package for octave is called fix this?

I already have that installed. I did ``sudo apt-get install liboctave-dev``` but it is already installed!

**Comment by cbm755** [comment]
Ok.  I'm not sure how to debug this further...

I checked a ubuntu box at work (14.04): `libc-dev` and `libgcc-dev` packages seem to provide `stdint.h` (in `/usr/local/` and `/usr/lib/gcc/...` respectively).  Do you have both those packages?

Do other octave-forge packages install correctly with `-forge`?

**Comment by cbm755** [comment]
I split off the Makefile issue to a new issue #134.

**Comment by genuinelucifer** [comment]
> libc-dev and libgcc-dev packages seem to provide

apt-get could not find libgcc-dev and replaced libc-dev with libgcc6-dev which is already the latest version.
I am trying to install a few packages with ```-forge``` but they require octave>=4.0.0 and on my ubuntu 14.10 I seem to get only upto octave 3.8.1! I will try with some other packages...

**Comment by catch22** [comment]
This doesn't resolve your problems, but you should be able to get a recent Octave from the following PPA: https://launchpad.net/~octave/+archive/ubuntu/stable

**Comment by genuinelucifer** [comment]
Thanks. Will try that.

**Comment by cbm755** [comment]
I could just bump the minimum Octave to 4.0.0, especially now that 14.04 is *not* the most recent Ubuntu LTS.  @catch22 that ok?  (I don't particularly want to try to support old Octave).

**Comment by catch22** [comment]
Definitely ok for me.

We could still accept patches to improve support for older Octave as long as they don't make the code appreciably more difficult to maintain.
