### ISSUE TITLE
deprecate DOCTEST_MATLAB/DOCTEST_OCTAVE

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#138]
After #137, we don't need them.  Possible replacements:

`XFAIL_IF(~(exist ('OCTAVE_VERSION', 'builtin')))`

`XSKIP_IF(is_octave())`

[edited]

1. We could document the 2nd one in `help doctest`: `Doctest provides a convenience function @code{is_octave()}, but you can access arbitrary variables and...`

2. We could deprecate in the sense of removing from "help doctest" but leave it supported (and leave tests in place).

@catch22, I think you use these features: what do you think?

**Comment by catch22** [comment]
Great! Just to be sure, the above should read `XFAIL_IF(...)` rather than `XFAIL(if ...)`, right?

The fact that `is_octave` is a private function but still reachable from the tests is somewhat cute (too cute? :smile:?) and avoids having to add a `doctest_` prefix...

**Comment by catch22** [comment]
More to the point of your question: I think we are using DOCTEST_MATLAB in `test_long_rows.m`.

Upon reflection, I think that `is_matlab()` is semantically different from `is_octave()`. E.g., when excluding a doctest due to a MATLAB bug/misfeature we might want to skip based on the former. So I think it might be good to keep the two constants for now?

**Comment by cbm755** [comment]
oops, editting...

**Comment by cbm755** [comment]
yeah, maybe too cute.  For example., anyone writing `%!` octave tests might be mislead into using it there too.

**Comment by cbm755** [comment]
re: semantically different: nothing stopping us from adding a too-cute `is_matlab()`...

**Comment by catch22** [comment]
Let's perhaps keep the constants for now. They are likewise defined in a local scope (only accessible by tests), but I think I like that the prefix makes it clear that they are defined by doctest. Would that be alright for you?

**Comment by cbm755** [comment]
Sure, works for me.
