### ISSUE TITLE
XFAIL_IF conditionals should not be allowed to contain % and #

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#144]
From #141:

> I concur that breaking on % and # should be lead to a behavior that will lead to fewer corner cases.

So we want these to work:
````
% doctest: +XFAIL                  % comment (with parenthetical)
% doctest: +XFAIL_IF (foo)    % comment
% doctest: +XFAIL_IF (foo)    % comment (with parenthetical)
````
The last one currently fails (it globs up to `... parenthetical)` because of limitations in our parser regex).

Downside is we might have disallow is this:
````
% doctest: +SKIP_IF (strcmp(sprintf('%d', 42), '42')))
````
(perhaps not explicitly disallow; rather a known bug)

**Comment by catch22** [comment]
That would be fine for me (can't think of good reasons for having complicated tests in the SKIP_IF conditional!).
