### ISSUE TITLE
failures if a test does `clear`

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#149]
```
>> pwd
ans = /mnt/files/export/src/octave.hg/doc/interpreter

>> doctest var.texi
Doctest v0.4.1: this is Free Software without warranty, see source.

var.texi ............................................... error: structure has no member 'want'
error: called from
    doctest_run>DOCTEST__run_impl at line 147 column 26
    doctest_run at line 85 column 9
    doctest_collect at line 155 column 11
    doctest at line 278 column 11
error: evaluating argument list element number 1
error: called from
    doctest_run>DOCTEST__run_impl at line 147 column 26
    doctest_run at line 85 column 9
    doctest_collect at line 155 column 11
    doctest at line 278 column 11
>> 
```

Seems to be at `clear foo b*r` but haven't investigated carefully.

**Comment by cbm755** [comment]
This is because it uses `clear`.  Not sure what we can do about that...  We support `clear foo` but if test uses `clear` we lose our various `DOCTEST__` variables.

Example:
````
@example
foo = 1
  @result{} foo =  1
bar = 2
  @result{} bar =  2
@end example


@example
@comment doctest: -TEXINFO_SKIP_BLOCKS_WO_OUTPUT
clear foo
@end example


@example
foo
  @print{} ... undefined ...
@end example


@example
@comment doctest: -TEXINFO_SKIP_BLOCKS_WO_OUTPUT
clear
@end example


This currently fails because of the above @code{clear}.
@example
bar
  @print{} ... undefined ...
@end example
````

**Comment by catch22** [comment]
We might be able to fix this by hiding all local variables someplace else. Might give this a try on the weekend.

**Comment by cbm755** [comment]
Just FYI, I seem to remember Matlab at least had some kind of private space for apps.  Not sure in about Octave.

Worst case, dump to disk if the command matches some `clear` regex.

**Comment by catch22** [comment]
I was thinking that either global variables or, more robustly, persistent local variables might work. The latter would be some variation on
```matlab
function doctest_var(write)
persistent x;
if write
  x = varargin{2};
end
return x;
end
```

**Comment by cbm755** [comment]
`clear all` will kill those?

**Comment by catch22** [comment]
I hoped that at least standalone `clear` without `all` would not (but I'm not sure)...

**Comment by cbm755** [comment]
That should work and I agree surviving (just)  `clear` is a good start!

**Comment by cbm755** [comment]
There was a [related thread on the maillist](http://octave.1599824.n4.nabble.com/Can-I-protect-specified-variables-from-quot-clear-all-quot-td4678582.html) recently.  Seems like `mlock()` might be a possible solution to surviving `clear all`.

See also https://savannah.gnu.org/bugs/index.php?48542

**Comment by catch22** [comment]
Wonderful, great catch! From what I understand, `mlock` seems to lock `persistent` variables.

**Comment by cbm755** [comment]
Great!  I was curious so I tested this a bit: at least on Octave, the persistent variables does survive "clear all" done from within `evalc` (as expected).  We should be good to go with this.

(Surprisingly to me, it also survives `clear all` done within its own scope.)

````
function mypers ()
persistent A
mlock()

if (isempty(A))
  disp('init')
  A = 0;
end

A = A + 1

if (rand() > 0.75)
  disp('doing some "clear all"')
  clear all
  S = evalc('clear all')
end

end
````

**Comment by cbm755** [comment]
I spoke too soon.  You cannot access `A` after the clear *during this call*, which is our use-case.

On Octave, it seems we can bring it back using another call to `persistent`:
````
function mypers2 ()

  persistent A
  mlock()

  if (isempty(A))
    disp('init')
    A = 0;
  end

  A = A + 1

  if (rand() > 0.75)
    disp('doing some "clear"')
    %clear
    %clear all
    S = evalc('clear')
    S = evalc('clear all')

    % A will be here next time we call the function
    % BUT we cannot access it right now
    %A

    % But on Octave, we can bring it back with:
    persistent A
    A
  end
end
````

But on Matlab, this gives an error: `The PERSISTENT declaration must precede any use of the variable A. `

**Comment by cbm755** [comment]
Maybe we should just rewrite the tests before running them.  Something like `s/clear/clear -exclude DOCTEST_*/` on the test source.

**Comment by catch22** [comment]
Here is another attempt:

```matlab
function mytest()

  mlock()
  persistent A = 0;

  A = A + 1
  subfun
  A


  function subfun()
    disp('doing some "clear"')
    evalc('clear')
    evalc('clear all')
  end
end
```

Output (Octave 4.2.1):
```
$ octave mytest.m 
A =  1
doing some "clear"
ans = 
ans = 
A =  1
```

**Comment by cbm755** [comment]
Works with Octave master too; seems to avoid eval-in-non-nested local functions #167.

**Comment by catch22** [comment]
Hm, I didn't quite manage to make it work in `doctest_run_tests`.

**Comment by cbm755** [comment]
I'm trying your "setter/getter" idea with mlock'd persistent vars, so far so good, will push PR later...

**Comment by cbm755** [comment]
And I was wrong about Octave master: you cannot do `evalc('a = 5')` in the nested function, just like #167.
