### ISSUE TITLE
Too many uninitialized variables warning when installing/using doctest

### ISSUE THREAD

**Issue by genuinelucifer** [catch22/octave-doctest#158]
I get `Use of uninitialized value in lc at /usr/lib/perl5/5.8/utf8_heavy.pl line 123.` when I try `pkg install -forge doctest` and also when running doctest.
.
I am using octave 4.2.0-rc1 on windows 10.
.
This warning is repeated too many times...

**Comment by oheim** [comment]
This warning appears during package installation when some function's docstring contains certain UTF-8 multibyte characters and is an upstream bug in either Octave or Texinfo.

As a user you can safely ignore the message.
