### ISSUE TITLE
`doctest .` should find tests in compiled oct files

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#178]
@mtmiller said:

> Would also be nice if doctest could automatically find compiled
> functions in oct files.

[pytave project](https://bitbucket.org/mtmiller/pytave/) has an example of what should work:

> As it is now, need to do both `doctest .` and `doctest ({'pycall', 'pyeval', ...})`.

**Comment by mtmiller** [comment]
A few days ago I looked a little bit into whether this would be worth fixing or not.

The part that already works: `doctest foo`, where `foo.oct` is a compiled function in the load path, `doctest` finds the function, parses the help text, and does the right thing.

The more tedious part is turning a directory of oct files (can mex files have doc strings?) into a list of function names to test. Could look at the array returned by `autoload` and extract a list of functions corresponding to each matching oct file, along with the oct file name itself.
