### ISSUE TITLE
Improve repository settings

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#186]
@catch22 can you change the github settings to:
- [x] give @mtmiller commit access?  Might be helpful for him to be able to push to dev branches directly.
- [ ] consider protecting the master branch so we have to go through PRs, to prevent us from pushing directly to it (e.g., by accident).
- [x] Have Travis CI do a weekly "cron" run in case of changing dependencies.

**Comment by catch22** [comment]
What are your current thoughts regarding protecting the master branch? So far I think we've been doing well with regards to committing simple things directly and using PRs for larger and/or more controversial changes, but I don't have a strong feeling either way.

**Comment by cbm755** [comment]
No strong feelings, shall we just close this for now?  Re-open if it becomes a problem, or one of us develops a stronger feeling about this.
