### ISSUE TITLE
Make install broken

### ISSUE THREAD

**Issue by catch22** [catch22/octave-doctest#189]
I get the following error message (GNU Octave, version 4.4.1 on the latest OS X Mojave):

```bash
~/Code/octave-doctest (master) make install
mkdir -p "tmp"
Creating package version 0.6.1 release ...
rm -f -r "tmp/doctest-0.6.1"
git archive --format=tar --prefix="tmp/doctest-0.6.1/" HEAD | tar -x
rm -f "tmp/doctest-0.6.1/README.matlab.md" \
	      "tmp/doctest-0.6.1/.gitignore" \
	      "tmp/doctest-0.6.1/.travis.yml" \
	      "tmp/doctest-0.6.1/.mailmap" \
	rm -f -r "tmp/doctest-0.6.1/util"
rm: tmp/doctest-0.6.1/util: is a directory
make: *** [tmp/doctest-0.6.1] Error 1
```

Not sure how to debug this. @oheim, any thoughts?

**Comment by mtmiller** [comment]
This line

    	      "tmp/doctest-0.6.1/.mailmap" \

should drop the trailing backslash.

**Comment by catch22** [comment]
Thanks for spotting this. Permalink:

https://github.com/catch22/octave-doctest/blob/e978f7b00e1ea00b166f5ee3f6917331ab26c415/Makefile#L74
