### ISSUE TITLE
quiet by default with 3 outputs?

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#201]
```
>> [nump, numt, summary] = doctest(...);
```
Maybe this should not show all the output?  Surely anyone running it like that is doing something programmatically (like a CI run) and doesn't want to see all the output.

We could have a `-quiet` directive (maybe not API listed in `help doctest`) which defaults to on when `nargout == 3`?

Or even when `nargout != 0`?

**Comment by cbm755** [comment]
@catch22, @mtmiller and @apjanke what do you think?  Seems to me it might be useful to run the tests but don't scream on the stdout about it...

My PR allows `[n, t, summary] = doctest({'foo', 'bar'}, '-quiet')` and `doctest foo -quiet`.

The question is really should this be the default if `nargout != 0`.  Then I can do `if (doctest ('foo')) ...` quietly.

**Comment by catch22** [comment]
This sounds good to me, including defaulting to it.

We should also document the "user interface flags" like `-quiet` and `-nonrecursive` that do not change the actual testing behavior (unlike the deprecated ones). If you agree I can open a separate ticket for this.

**Comment by cbm755** [comment]
Sure file a separate issue and we'll discuss but we made need `-verbose`: e.g., in a CI run, I want the `SUCCESS=doctest(...)` form which will now default to quiet.  But I'd also like the verbose output in the logs so that if it fails, I can look at it...

I guess a compromise that DTRT is `nargout == 3` implies quiet?  But `nargout <  3` does not.

**Comment by catch22** [comment]
Yes, that's what I meant with my comment on the PR.

**Comment by cbm755** [comment]
Ok, this is done, closing, open new issues for further changes
