### ISSUE TITLE
[maint] port CI to new docker images

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#204]
@mtiller, let's do doctest first b/c it does not depend on Python etc so should be simpler.

I played with this a little, did:
```
sudo docker run --volume=$PWD -it mtmiller/octave
```
This makes PWD appear inside the container, but it is empty.  Probably I just need to read some docs...

But I'm a bit uncertain whether we should:
  1. run `docker --volume ... mtmiller/octave octave --eval...`  [updated to clarify]
  2. run docker, mount the pwd, do `make test` from bash inside the container.
  3. "make dist" and then install that .tar.gz package inside the container...  

Actually I'm a bit unsure about this in general: are Octave packages supposed to be fully testable from the dist tar.gz file?  But the dist .tar.gz file does not contain the Maintainers Makefile...

In some sense #3 seems better, and closer to a world where `pkg test doctest` DTRT...

Thoughts?  Feel free to start a PR if you have a strong sense of how this *should* work.

**Comment by mtmiller** [comment]
Yes, this looks like a simple starting case, will work on a PR.

**Comment by cbm755** [comment]
For the record, you chose something like #1 on my list, but using the Makefile.

**Comment by mtmiller** [comment]
Yeah, the general answer is "it depends", not all will be as lightweight as this one.
