### ISSUE TITLE
Bad skip condition definition can abort entire test run

### ISSUE THREAD

**Issue by apjanke** [catch22/octave-doctest#205]
The [doctest code that decides whether a test is skipped](https://github.com/catch22/octave-doctest/blob/55a8f089b2f581f5134532fad9431eefeb4a5b68/inst/private/doctest_run_tests.m#L47-L51) is an unprotected eval.

```
  % determine whether test should be skipped
  % (careful about Octave bug #46397 to not change the current value of “ans”)
  eval (strcat ('DOCTEST__current_test.skip = ', ...
                 doctest_join_conditions(DOCTEST__current_test.skip), ...
                ';'));
```

This means that an error in a tested file's skip condition definition will bubble up to the top, and abort the entire test run. This condition occurs with the doctest code in the Octave Forge interval and symbolic packages.

Maybe this `eval()`, and the others in `doctest_run_tests`, should be protected by a try/catch that turns a bad skip or xfail definition into a test failure, instead of aborting the run?

Caused https://github.com/apjanke/octave-testify/issues/44.

**Comment by mtmiller** [comment]
I think `eval` might also need to be fixed to do the protection itself. This was brought up in [Octave #55939](https://savannah.gnu.org/bugs/?55939), if I understand the author, `eval` in Matlab does catch errors.

**Comment by apjanke** [comment]
That‘s a surprise to me. Matlab `eval` normally throws errors. I think they’re encountering an undocumented Matlab behavior related to an undocumented second argument to `eval` there. Normally, it's only `str2num()` that doesn't throw errors, and that’s probably because str2num is internally try/catching the `eval(...)` that it does.

**Comment by mtmiller** [comment]
Ok, unclear to me, fair to continue under the assumption that `eval` may raise an error.

**Comment by cbm755** [comment]
At the very least, surely syntax errors in the str must raise errors outside eval so I think we (Doctest) should do try-catch here.

Maybe do the "EXTRACTION_ERROR" on catch.

**Comment by apjanke** [comment]
The fix looks good to me.
