### ISSUE TITLE
tweak source so checklicense script works

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#215]
`checklicense -r inst/`:
```
./inst/private/doctest_collect.m: UNKNOWN
./inst/private/doctest_colors.m: UNKNOWN
./inst/private/doctest_compare.m: UNKNOWN
./inst/private/doctest_datastore.m: UNKNOWN
./inst/private/doctest_default_directives.m: UNKNOWN
./inst/private/doctest_format_exception.m: UNKNOWN
./inst/private/doctest_join_conditions.m: UNKNOWN
./inst/private/doctest_run_docstring.m: BSD 3-clause "New" or "Revised" License
./inst/private/doctest_run_tests.m: BSD 3-clause "New" or "Revised" License
./inst/private/is_octave.m: UNKNOWN
```

The files that are UNKNOWN have something like `% This is Free Software, BSD-3-Clause, see doctest.m for details.`
Whereas this works:
`% License: BSD-3-Clause, see doctest.m for details.`

**Comment by mtmiller** [comment]
I've started using [SPDX-License-Identifier](https://spdx.org/using-spdx-license-identifier), just throwing that out there as a possible "standard". Unfortunately the licensecheck script doesn't handle that tag yet, but it is very easy to grep for.

**Comment by cbm755** [comment]
Thanks.  I've tried that in Symbolic; I cannot find something that works for GPL3+, I'll open a bug and CC you...
