### ISSUE TITLE
Make matlab_pkg fails on MacOS

### ISSUE THREAD

**Issue by skycaptain** [catch22/octave-doctest#224]
I've checkout out the current `master` and tried to run `make matlab_pkg` on MacOS 10.14.6 (Mojave). Got the error:

```shell
...
Converting texinfo to Matlab-style documentation: doctest.m
cp -ra inst/private/*.m tmp/doctest-matlab-0.7.0+/private/
cp: the -R and -r options may not be specified together.
make: *** [tmp/doctest-matlab-0.7.0+] Error 1
```

`-a` on MacOS equals `-pPR` according to `man cp`. A workaround is to install `coreutils` e.g. via Homebrew and then run `env PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" make matlab_pkg`

In some way related to #216.

**Comment by cbm755** [comment]
Thanks!  Any chance you can send a pull request?

I don't have a mac so not easy to test.  But if you send a pull request, I can test to ensure it still works on GNU systems.

**Comment by skycaptain** [comment]
I'll try. Also, AFAIK since MacOS is a BSD derivate, the cp command is the same on MacOS and e.g. FreeBSD; just in case you want to try it yourself.

**Comment by catch22** [comment]
I can test it on macOS (but do not have time right now to implement the fix myself).
