### ISSUE TITLE
matlab: logical printing changed?

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#234]
```
    logical.mynewmethod ................................ FAIL    2/3   

   >> mynewmethod(true)

      expected:     ans = 0

      got     : 
ans =

  <a href="matlab:helpPopup logical" style="font-weight:bold">logical</a>

   0



   >> islogical(ans)

      expected:     ans = 1

      got     : 
ans =

  <a href="matlab:helpPopup logical" style="font-weight:bold">logical</a>

   1
```
Is this similar to #231?   @skycaptain said there were other failures too...

**Comment by cbm755** [comment]
Right, this is https://savannah.gnu.org/bugs/?56974 already filed upstream Octave.
```
>> logical(1)

ans =

  logical

   1

>> logical(0)

ans =

  logical

   0

>> false

ans =

  logical

   0
```

I wonder why this did that instead of 
```
ans = 

   logical

    false
```

**Comment by cbm755** [comment]
Maybe these tests should be:

```
...0
```

so the ELLIPSIS directive matches the `logical`

**Comment by skycaptain** [comment]
This one is tough. This would of course be a valid and quick fix for doctest. But, I could also imaging people looking at these tests, seeing them as examples on how to write a good doctest, and thinking testing against trailing `0` is just enough. Maybe the tests should cast the logical to double? This will print just the numbers:

```matlab
>> double(logical(1))

ans =

     1

>> double(logical(0))

ans =

     0

>> double(false)

ans =

     0
```

**Comment by cbm755** [comment]
I'm not too worried about that; I don't think of the tests as documentation (except the ones in `doctest.m` itself of course).

Someday we should write a manual (#129) which could have a section on "# Writing doctests for both Matlab and Octave".

**Comment by catch22** [comment]
I think we should try that our doctests are as idiomatic as possible. For this reason I think I'd prefer @skycaptain's solution.

In some sense it's great that our tests catch when upstream Octave becomes out of sync with matlab. 😄 I hope that whenever this happens and we "fix" our tests, a test gets added to Octave instead...

**Comment by cbm755** [comment]
@skycaptain did you have time to do this?

**Comment by skycaptain** [comment]
I'm sorry; do what?

**Comment by skycaptain** [comment]
I could make a PR. Which solution do you prefer?

**Comment by cbm755** [comment]
@catch22 [prefers your solution](https://github.com/catch22/octave-doctest/issues/234#issuecomment-538052690) (that is wrapping in `double`) so let's go with that.

Thanks!
