### ISSUE TITLE
upstream Octave changes to error

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#245]
http://hg.savannah.gnu.org/hgweb/octave/rev/fd32c1a9b1bd

Does this effect us in any way?

**Comment by mtmiller** [comment]
I'll push a new devel Docker image soon so you can find out.

**Comment by mtmiller** [comment]
Yes, tests are failing in the development version, but only tests in `test_error.texinfo` added in #244 :open_mouth: I haven't built Octave locally in a while, I'll see if I can do that and figure out what's different.

**Comment by cbm755** [comment]
I've got it built locally, will play with this... eventually.  But go ahead if you want!

**Comment by mtmiller** [comment]
Here is a summary of the differences. So small, but breaking expected output. Maybe we should try to push back on one or both of these upstream?

Octave 5.1 has no comma between line and column number, and 5 significant digits:

```
>> nosuchfcn (42)
error: 'nosuchfcn' undefined near line 1 column 1
>> inv (3)
ans = 0.33333
```

Octave 6 now has a comma between line and column, and only 4 significant digits now:

```
>> nosuchfcn (42)
error: 'nosuchfcn' undefined near line 1, column 1
>> inv (3)
ans = 0.3333
```

**Comment by mtmiller** [comment]
I've commented on [octave#56936](https://savannah.gnu.org/bugs/?56936) related to the change in the default numeric format.
