### ISSUE TITLE
add tests for the utf-8 doctest with cp1252 test

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#253]
In #251 I said:

> I think we will want some unit tests of CP1252 encoded input working correctly.

**Comment by cbm755** [comment]
BTW, those tests may fail on Octave <7: that would be acceptable but might need some finessing for our CI

**Comment by mmuetzel** [comment]
Octave doesn't seem to recognize `CP1252` as an encoding identifier (at least for me). Maybe, better use `iso-8859-1` which is basically the same encoding but works here.

**Comment by cbm755** [comment]
Fixed by #256, thanks @mmuetzel

**Comment by mmuetzel** [comment]
Afaict, this test doesn't do anything meaningful in any released version of Octave. Is that intended?
