### ISSUE TITLE
encoding tests on Octave < 8

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#257]
Afaict, this test doesn't do anything meaningful in any released version of Octave. Is that intended?

Edit: some background: I wrote that test specifically to have a workaround for the behavior in Octave 7. It should be working "out of the box" without any workarounds in Octave 8. If I understand the version check you added correctly, it should the main part of the test in Octave 7 and earlier.

_Originally posted by @mmuetzel in https://github.com/catch22/octave-doctest/issues/253#issuecomment-1186800949_

**Comment by cbm755** [comment]
@mmuetzel oh sorry.  I may have missed the point.

Will investigate further...  Some effort may be needed the silence the warnings on Octave 7 then (?)    And I guess better logic to test it directly without the `addpath` on Octave 8.

**Comment by mmuetzel** [comment]
IIUC, this test won't work on Octave before version 7. So, it is probably save to keep skipping them for those versions.
It should run correctly on version 7 and later.
Essentially, that means that the test could be guarded with `compare_versions (OCTAVE_VERSION(), '7.0.0', '>=')` (where it was `compare_versions (OCTAVE_VERSION(), '8.0.0', '>=')` before).

I'm not sure, I understand the changes you made. Could you please elaborate a bit?

**Comment by cbm755** [comment]
Will try to do so in #258.
