### ISSUE TITLE
change default branch

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#274]
@catch22 can you change the "default branch" under Settings from `master` to `main`?

On one of my other repos it looks like this:

![image](https://user-images.githubusercontent.com/818622/210308786-2f42ce9b-d998-4a2a-a586-26aae0eef2ad.png)

**Comment by catch22** [comment]
Happy new year! There is also an option to rename to master branch to main. Would this be easier on the history? Which one would you prefer?

**Comment by cbm755** [comment]
And to you!

I'm not sure: I've been pushing both in-sync.  So maybe it won't really matter, or maybe it won't let you rename since I created a `main` branch...

**Comment by cbm755** [comment]
While you're at it, maybe add @mmuetzel as a collaborator?  They are an Octave dev and have been following my changes: I think its generally good to increase ownership of these projects.

**Comment by catch22** [comment]
Added @mmuetzel and changed the default branch to `main`. Shall we delete `master` to avoid confusion?

**Comment by catch22** [comment]
PS: I think some time ago we discussed moving this repo to an organization; this would allow us to give you (and possibly others) admin privileges, unlike with a personal repo like this one. I forget why we didn't pursue this further, perhaps because at the time we were thinking of getting `doctest` added to octave proper? Worth pursuing this idea again?

**Comment by cbm755** [comment]
Yes let's delete master.

**Comment by cbm755** [comment]
I've been thinking the same about https://github.com/cbm755/octsympy

How much breakage does one get?  Anyone with a remote clone needs to do some updating for the new URL...

**Comment by cbm755** [comment]
Closing as this is done.  Other discussion can continue at #277.
