### ISSUE TITLE
OctaveForge package design

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#29]
@catch22 Let's (eventually) pick one of these.

- [x] we can be a Octave package that also generates a Matlab-appropriate zipfile for releases.  Code could live in `inst/`, various other rules.  PR #34.
- [x] ~~we can be a continue as a Matlab package (note this is not well-defined) and have some script that generates Octave packages.~~  [going with first approach].

Also:

- [x] In Octave, we will probably be "Octave-Forge Doctest Package" or something like that.  [sort of done in `DESCRIPTION` file].
- [x] The "official" software name is "Doctest For Matlab".  License.txt refers to this for example.  ~~Is there any legal problem problem here?  [no]~~
- [x] Do we want a new name that is less confusing? [yes, the repository is now called `octave-doctest`.]
- [x] If new name, do we keep the original License.txt and have a new COPYING?  [No, just attribute to @tgs and keep copyright notices up-to-date.]
- [x] Move `DESCRIPTION` file to root. 4f1bc7929c4d0e867f08e63bbce9d6fc29b8ed6b

**Comment by catch22** [comment]
I would be happy for us to be an Octave package. (I understand that for Matlab users, the only change required is to add the `inst/` subdirectory to the PATH.)

**Comment by catch22** [comment]
I believe the license is the 3-clause BSD license. My understanding is that we are free to modify the sources, rename the software (e.g. we might rename the repository to `doctest-for-octave`), and distribute the result as long as we make sure to preserve the original copyright and license statements. However, IANAL :smiley:

**Comment by cbm755** [comment]
I agree that it is 3-clause BSD.  But also IANAL.

But that would be a fork for sure.  

Names: "octave-doctest" or perhaps try to avoid both octave and matlab: "doctestm", "doctestem", "Doc Test'em" -- ala Duke Nukem :)

**Comment by catch22** [comment]
I like these names ;)

I recall that you had contacted Thomas Smith a little while ago. Did he get back to you at all?

**Comment by cbm755** [comment]
I wrote to him on some contact form on BitBucket.  But maybe that just goes to /dev/null.

I notice he has a github account: so ping @tgs 

Here's my message:

````
Hi Thomas,

Thanks for this code. Are you still interested in maintaining it?

I've been making a few changes to better-support Octave. Currently, we have two octave forge packages using this for testing, with a rough idea to have the full Octave core using doctests eventually.

I've also been fixed bugs that are true on Matlab as well.

I've been organizing this around catch22's github clone but could organize it elsewhere (i.e., your bitbucket).

thanks again,

Colin
````

**Comment by cbm755** [comment]
@catch22 and I'm sorry that should have said "*we* have been organizing".

**Comment by catch22** [comment]
It would be great if he's onboard with our changes!

**Comment by oheim** [comment]
It is very important to have this as an Octave Forge package. To have an installable and loadable package is necessary if documenation checking shall be available to more than one developer in an easy way (which is a prerequisite for using it).

Otherwise everybody would have to download it manually and we have to mess with load paths in everybody's workspace.

**Comment by catch22** [comment]
Hi Oliver,

rhis discussion was purely about the organization of the repository (and not about whether doctest should be available on OctaveForge). However, we agreed on organizing the repository in the "standard" OctaveForge way.

**Comment by oheim** [comment]
@catch22 Okay, I just wanted to leave that comment somewhere ;-)

IMHO you have to choose a new name (clause 3), must not name T. Smith as the package author (clause 3) and keep the copying conditions (clause 1) as well as the copyright statements of course.

However, you may use GPL for new function files in the package, because the license is compatible with GPL.

**Comment by catch22** [comment]
@oheim Thanks, that was very helpful. So unless @tgs endorses this modified version, is the following procedure correct?

1. Rename the project to something different than `doctest-for-matlab` before we distribute it on octaveforge (as to not violate clause 3).
2. Keep the current content of COPYING and possibly add a copyright statement next to the existing one.
3. Remove all attributions to @tgs from [doctest.m](https://github.com/catch22/doctest-for-matlab/blob/master/inst/doctest.m) (as this would violate clause 3).

(I want to keep the license as BSD.)

**Comment by oheim** [comment]
1. Good. Please choose a simple name like “doctest”. That benefits installation and usage.
2. That's complicated in general, but if you plan to keep everything under the same license, you can (and should) just add copyright statements there.
3. Clause 3 says that you shall not advertise @tgs as the package creator anymore. That is, you shall not name @tgs in the DESCRIPTION file for example. It is okay to give attribution. 

I am not familiar with the BSD-style licenses, but it's probably not needed to have a separate CONTRIBUTORS file when you have copyright statements from all contributors in COPYING.

**Comment by cbm755** [comment]
But if the name is simple ("doctest") then I don't think we can realistically claim this in the license:

````
Neither the name of Doctest nor the names of its contributors may be
used to endorse or promote products derived from this software without specific
prior written permission.
````
E.g., given that doctest is already used in Python community.

I wonder if its still "modified BSD" if you just put:
````
The names of the contributors may not be
used to endorse or promote products derived from this software without specific
prior written permission.
````
I dislike license proliferation so probably bad idea to be rolling our own.

**Comment by cbm755** [comment]
See PR #36 for some copyright updates.

**Comment by oheim** [comment]
With the simple name the product name stuff should be removed from the license. Then it will be an exact [ModifiedBSD] (http://directory.fsf.org/wiki/License:BSD_3Clause).

**Comment by cbm755** [comment]
I don't really understand Octave pkg naming.  Because things often have generic names like "image" or "interval", which is good within Octave.  But then outside, should they be called the "Octave-Forge Image package"...  @oheim opinion?

**Comment by oheim** [comment]
It's a local name within the octave forge namespace. For example Debian packages will then carry the name octave-_packagename_. And in any kind of documentation you have to say “Octave Forge _name_ package” to make clear what you mean. I personally like the simple names as long as the name matches the content.

However, you should probably ask Carnë about the actual backgrounds and conventions.

**Comment by cbm755** [comment]
Thanks @oheim.  @catch22 so how about:

1.  rename github project to: catch22/octave-doctest

2.  package name: "doctest".  e.g., in DESCRIPTION file, so users do "pkg install -forge doctest".  Simple.

3.  clone on sourceforge.net gets called "doctest"  (`git.code.sf.net/p/octave/doctest`)

3.  in longer form (i.e., README.md) we refer to it as "the Octave-Forge Doctest package".

4. Matlab package is just called "doctest" (e.g., doctest-0.3.0.zip).

Does that sound reasonable?  We can also run it by Carnë when I ask him to setup the sourceforge stuff.

**Comment by oheim** [comment]
Sounds all good to me.

**Comment by cbm755** [comment]
> (I want to keep the license as BSD.)

For the record, I prefer GPLv3+ but am happy enough with Modified BSD.

**Comment by tgs** [comment]
Hi! I'm terribly excited that you folks are making an Octave version!  I don't use Matlab or Octave at work any more, so I don't want to be in charge of anything. Fork with all my blessings!

@psexton has an active fork of this plus Matlab-xunit going, I think he's been mostly focused on making it work with non-ancient versions of Matlab, and fixing bugs. That system uses classdef, so maybe it still doesn't work in Octave?

My interpretation of that part of the license is simply that you can't advertise your version as "Thomas Smith's Doctests for Matlab!" That said, I would be happy to give you another license, eg 2-clause BSD. Let me know.

**Comment by cbm755** [comment]
Thanks @tgs.    I was not aware of the other fork, thanks for that.

I don't think another license from you is needed, but appreciate the offer.

**Comment by cbm755** [comment]
@catch22 So do you think we should rename the github project to "octave-doctest"?  We should do so before an 0.3.0 release...

Upstream Octave has preference for mercurial so you might consider switching to that.  (I have no strong opinion either way).

**Comment by catch22** [comment]
@tgs Thanks for the kind reply!

@cbm755 That sounds good to me. Should I just go ahead and rename the repository?

**Comment by cbm755** [comment]
> Should I just go ahead and rename the repository?

Sure!  There may be some fallout but I think it mostly effects @oheim and I: we'll deal with it.

**Comment by catch22** [comment]
Done; travis-ci is running again & I've fixed some links.

**Comment by cbm755** [comment]
Thanks!
