### ISSUE TITLE
ANSI colors vs. Octave's pager

### ISSUE THREAD

**Issue by catch22** [catch22/octave-doctest#33]
My adding error colors around the "got" does not play well with Octave's pager.

**Comment by cbm755** [comment]
:(  I never use a pager so didn't notice.  I guess technically we can detect PAGER use...

**Comment by cbm755** [comment]
`if (~page_screen_output())` in the same place we check for color TERM?   Maybe we will lose colour on travis though :(

**Comment by catch22** [comment]
I think I had to use `more off` to turn it off. Maybe let's leave it as is until someone complains...

**Comment by catch22** [comment]
Hmm, I believe we should check for isatty() in addition to the TERM environment variable. Unfortunately, I do not know how to do this with Octave.

**Comment by catch22** [comment]
For now, just use `export LESS='-R'` to make the pager play nice with ANSI colors. In the future we might like to come up with a more clever solution.
