### ISSUE TITLE
Model functionality after Octave's test function and add rundoctests wrapper

### ISSUE THREAD

**Issue by catch22** [catch22/octave-doctest#37]
- [x] Remodel the API and functionality of `doctest` to follow http://octave.sourceforge.net/octave/function/test.html (PR #38).
- [ ] Add `rundoctests` or `__run_doctest_suite__` in the spirit of http://octave.sourceforge.net/octave/function/runtests.html (PR #52).
- [ ] Use `rundoctests` in the `Makefile`.

Cf. previous discussions in #31.

**Comment by catch22** [comment]
@cbm755 I am thinking of remodeling the API of `doctest` and `rundoctests` to follow `test` and `runtests` (but to allow `doctest` to work on a cell array of targets rather than a single target only).

 Do you think that is sensible?

**Comment by catch22** [comment]
I am working on this in the `new-api` branch at https://github.com/catch22/octave-doctest/tree/new-api and will do a pull request before committing.

**Comment by cbm755** [comment]
Sounds sensible to me!  Let's make a 0.3.0 release before merging this.  But we don't need to post on Octave-Forge if you'd rather have the new API in place first.

**Comment by catch22** [comment]
Excellent. Should I give it a try following your recipe in https://github.com/catch22/octave-doctest/wiki/Development-Process? I'd suggest that we don't post on Octave-Forge before you and @oheim are happy with the new API.

**Comment by catch22** [comment]
Please see #38 for a suggestion.

**Comment by oheim** [comment]
FYI: I have made a private package from 4e4a5943321ed87b3db1f5892180b0d151da3328 and revised the interval package's [Makefile](http://sourceforge.net/p/octave/interval/ci/a9a7889d8aa4193980f3b9cd459754d9143971ca/tree/Makefile#l222) based on that package.

It works great and the only current drawbacks are that I have to write a simple workaround for suppression of the eval'ed code and have to generate the list of files to be tested in the Makefile (instead of using a recursive directory doctest wrapper).

**Comment by catch22** [comment]
@oheim @cbm755 Could we brainstorm a little bit about what kind of wrapper we should add? I understand that Octave comes with

1. A public `runtests` function that runs `test` on each file in the given directory (without recursion).
2. A (private?) `__run_test_suite__` function that is a more elaborate wrapper (including recursion, more detailed statistics, and which prints all error messages into a log file).

Is it desirable to have doctest versions of both functions so that we preserve Octave's test API (as much as possible)? How about we only provide a function called `rundoctests` which optionally supports recursion and a log file while defaulting to the behavior of `runtests`? E.g., something like

~~~
function rundoctests(directory, recursion=false, logfile='')
~~~

Thanks for your feedback.

**Comment by oheim** [comment]
A (single) public function with a well documented behaviour is my preferred solution. These are the use cases by target user groups:
* Recursive testing: Maintainers before the release or for continuous integration
* Logfile: Useful for reporting bugs. Is anybody going to report failing doctests to the maintainers at all? It depends whether the doctest are used to validate the software.
* Single directory, non-recursive: End-users with a simple directory of self-made functions
* Statistics: I don't care ;-) The most important point is to see whether there are errors or not. And it should be easy to tell whether the doctest did something useful. If errors are detected, they shall be easily located. This point has already been solved sufficiently, IMHO.

**Comment by catch22** [comment]
Closing this discussion, as we have decided not to go this route.
