### ISSUE TITLE
`doctest class` used to test methods, now doesn't

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#53]
strange "make test" passes.   But interactively:

````
>> doctest({'doctest', 'test_class'})

doctest ............................................................... PASS    6/6   
test_class ............................................................ EXTRACTION ERROR

    Function or class not found.


Summary:

   PASS    6/6   

1/2 targets passed, 0 without tests, 1 with extraction errors.

````

**Comment by catch22** [comment]
I think this is because test/ is not in your path when run interactively.

**Comment by cbm755** [comment]
No, 'test' is pwd in that example.  And all my Symbolic classes are broken too...

**Comment by cbm755** [comment]
`doctest @sym/mymethod` works but neither `doctest @sym` nor `doctest sym` work anymore.

**Comment by cbm755** [comment]
Gah, now it works, I must've had git in some weird state, sorry for noise.

**Comment by cbm755** [comment]
Reopen, seems broken with my hg octave checkout (default branch), but working with 3.8.2 install...  Will investigate

**Comment by catch22** [comment]
See my comments in https://github.com/catch22/octave-doctest/blob/master/inst/private/doctest_collect.m#L34 - perhaps this is relevant to the Octave breakage.

**Comment by cbm755** [comment]
Surely is...  

````
>> exist('sym', 'dir')
ans = 0
>> exist('@sym', 'dir')
ans =  7
>> exist('@sym')
ans = 7
>> exist('sym')
ans =  103
>> 
>> ver
----------------------------------------------------------------------
GNU Octave Version: 4.0.0-rc4
````

**Comment by cbm755** [comment]
The 103 thing is new c.f. Octave 3.8

**Comment by catch22** [comment]
With Octave 3.8.1, I have the following behavior:

~~~
octave> pwd
ans = /.../octave-doctest
octave> addpath /.../test
octave> exist test_class
ans =  2
octave> exist @test_class
ans = 0
~~~

but

~~~
octave> pwd
ans = /.../octave-doctest/test
octave> exist test_class
ans =  2
octave> exist @test_class
ans =  7
~~~

(which explains my comment).

**Comment by cbm755** [comment]
but your comment incorrectly implies that it doesn't work even if @class is a subdir of pwd...  I will see about a fix and reword slightly.

**Comment by catch22** [comment]
Sorry, that was bad wording on my side.
