### ISSUE TITLE
dot dot dot output too wide for 80 column terminal

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#54]
which is still often the default

**Comment by cbm755** [comment]
Maybe revert 5944d5c8bbbee23cc6ed15c36a48b10861d6cf03?

One can detect terminal width if you really want it wider, but I would suggest unless we have a good reason, that it might be better to keep it simple.

Messing with terminal width:
https://github.com/cbm755/octsympy/blob/master/inst/%40sym/display.m#L83

**Comment by catch22** [comment]
Reverted. The reason was that `rundoctests` is currently using absolute path names, but the commit creeped into master.
