### ISSUE TITLE
Octave: "fake_evalc" spams stdout

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#6]
`evalc` is supposed to capture the stdout and *not echo it*.  My `fake_evalc` fcn does the first but not the latter.  I don't see any easy way around this without doing something icky with PAGER.

The right thing to do is probably to [fix Octave](https://savannah.gnu.org/patch/?8033).

But if someone knows a quick workaround for `fake_evalc` then let me know...

**Comment by catch22** [comment]
I have fixed the problem when running `doctest` interactively from the octave prompt by setting `PAGER` appropriately. However, it seems that `PAGER` is not used when running code non-interactively.

**Comment by cbm755** [comment]
For the record: s/fixed/worked-around/  :)

(correct fix is upstream!)

**Comment by catch22** [comment]
That's right :)

**Comment by oheim** [comment]
I have a usable workaround. First, I must also set PAGER_FLAGS, because the default flags are not compatible with `cat` in my environment:
````
  % redirect stdout to /dev/null for the duration of this function
  fflush(stdout);
  PAGER('cat > /dev/null', 'local');
  PAGER_FLAGS('-', 'local');
  page_screen_output(1, 'local');
  page_output_immediately(1, 'local');
````

Then I can use the following recipe in my Makefile with octave. The `script` command lets Octave think it's being run in an interactive session.
````
	@echo "Testing documentation strings ..."
	@(echo "targets = '$(shell (ls inst; ls src | grep .oct) | cut -f2 -d@ | cut -f1 -d.) $(shell find doc/ -name \*.texinfo)';"; \
	  echo "targets = strsplit (targets, ' ');"; \
	  echo "doctest (targets)"; \
	  echo "exit") | script --quiet --command \
		"$(OCTAVE) --silent --path inst/ --path src/ --path $(DOCTEST_HOME)/inst" /dev/null
	@echo
````

A true solution would try to use an octave_parser and implement the evalc function (first in an oct-file, later in Octave core). You could start by looking at libinterp/parse-tree/oct-parse.in.yy.

**Comment by catch22** [comment]
The `script` trick is excellent. Is there a way to detect whether Octave is run interactively from within Octave? Then we could use this to change the buffering behavior depending on that.

**Comment by oheim** [comment]
````
try
    interactive = kbhit (1);
    interactive = true;
catch
    interactive = false;
end_try_catch
````

However, I prefer filtering the stdout with awk over the script trick.

**Comment by catch22** [comment]
I was thinking that we could use the PAGER override when in interactive mode, and otherwise fall back to the current behavior (until `evalc` has been implemented in Octave). Would this make sense or do you feel that this approach would be too fragile?

**Comment by oheim** [comment]
You could give it a try. After a first release more users should be using it and we'll see if it's stable. Please don't waste your time working on kludge when bug reports are coming in. Is #41 only related to the symbolic package?

P.S. On Microsoft Windows (`ispc ()`) you want to use `PAGER ('cat > NUL', 'local');`

**Comment by catch22** [comment]
Thanks for the Windows hint. I didn't understand your third sentence.

**Comment by oheim** [comment]
I am not sure how stable the whole “is the session interactive” and “use PAGER for output suppresion” thing is going to be. And since it is a workaround for the actual problem (no evalc function in Octave) and not working in all cases (non-interactive sessions), I would consider it a kludge. If it turns out to be not working, I prefer working on an evalc implementation over fixing bugs with that temporary solution.

On the other hand, if the PAGER works good within interactive sessions, that is already a great benefit for everybody who doctests interactively.

**Comment by catch22** [comment]
I have a similarly ambivalent feeling. Given #41, perhaps we best wait for Octave to provide a proper `evalc` implementation. Do you agree with the course of action?

PS: I have documented the current behavior in ce7a0b8466862d1abf0acd81dd0bce239d4afa44.

**Comment by cbm755** [comment]
I rather suspect [it won't get fixed](https://savannah.gnu.org/patch/?8033) unless we push/help upstream.  I think @oheim means contributing there might be more fruitful than banging away on kludges.

But OTOH even if we fix it now, it won't make Octave 4...

**Comment by catch22** [comment]
Hum.. what do you suggest as a course of action (I'm not familiar with Octave internals)?

**Comment by cbm755** [comment]
I'm not sure; I haven't been following what works and what doesn't.  What is important to me:

1.  Travis output is not interleaved (this is non-interactive I assume).
2.  Interactive input is not interleaved.

If you can hide the spam and satisfy those then I'm ok with a kludge.  I will investigate #41 bit further but master is bit broken for me atm...

**Comment by catch22** [comment]
Hum, what is broken?

**Comment by cbm755** [comment]
#53

**Comment by oheim** [comment]
I have looked into the code of Octave core. The PAGER solution is not that much of a kludge. However, I have managed to create an evalc implementation, that you could use with an oct-file in the package: https://savannah.gnu.org/patch/download.php?file_id=34015

**Comment by catch22** [comment]
Thank you. Maybe we can fall back to your implementation if `~exist('evalc')~.

**Comment by oheim** [comment]
Yes, that would be the preferred behaviour. We should test the evalc function in this package and, if it works, advertise it for [Octave core] (https://savannah.gnu.org/patch/?func=detailitem&item_id=8033).

**Comment by oheim** [comment]
Do you want to implement the oct-file yourself or would you prefer a pull request?

**Comment by catch22** [comment]
A pull request would be awesome, but I can also try to figure out things myself and pester you with questions :smile:

**Comment by oheim** [comment]
Whatever you prefer. I can provide a pull request easily, because I already know what to do. However, you can also learn something new and I don't want to stand in the way with that. ;-) The handling of oct-files is described in the Octave manual.

**Comment by catch22** [comment]
Please see PR #60.

**Comment by catch22** [comment]
Closing (PR #60).
