### ISSUE TITLE
warnings not working on evalc branch

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#61]
See recently pushed `test/test_warning.m`

**Comment by oheim** [comment]
I look into this issue.

**Comment by oheim** [comment]
I can make the warnings work (they are written to stderr, which is not captured by the initial version). However, I have a big problem making the function work under Octave 4 at all. Could you please check, whether doctest_evalc does something useful under Octave 4?

**Comment by oheim** [comment]
The following fixes the issue for warnings and errors as well. I have successfully tested it with Octave 3.8.2 (GNU/Linux) and Octave 4.0.0-rc4 (Windows). However, I get crashes in Octave development version on GNU/Linux. Maybe that's a problem with my setup.

````
diff --git a/src/doctest_evalc.cc b/src/doctest_evalc.cc
index 24e35b2..211b21d 100644
--- a/src/doctest_evalc.cc
+++ b/src/doctest_evalc.cc
@@ -25,7 +25,7 @@ DEFUN_DLD (doctest_evalc, args, nargout,
   "@deftypefnx {Loadable Function} {@var{S} =} doctest_evalc (@var{TRY}, @var{CATCH})\n"
   "\n"
   "Parse the string @var{TRY} and evaluate it as if it were an Octave "
-  "program.  If that fails, evaluate the optional string @var{CATCH}.  The"
+  "program.  If that fails, evaluate the optional string @var{CATCH}.  The "
   "string @var{TRY} is evaluated in the current context, so any results "
   "remain available after @command{doctest_evalc} returns."
   "\n\n"
@@ -52,9 +52,11 @@ DEFUN_DLD (doctest_evalc, args, nargout,
   if (nargin > 0)
     {
       // Redirect stdout to capturing buffer
-      std::ostream & stdout = octave_stdout;
+      std::ostream & out_stream = octave_stdout;
+      std::ostream & err_stream = std::cerr;
       std::ostringstream buffer;
-      stdout.rdbuf (buffer.rdbuf ());
+      std::streambuf* old_out_buf = out_stream.rdbuf (buffer.rdbuf ());
+      std::streambuf* old_err_buf = err_stream.rdbuf (buffer.rdbuf ());
 
       int parse_status = 0;
 
@@ -70,9 +72,15 @@ DEFUN_DLD (doctest_evalc, args, nargout,
         }
 
       // Stop capturing buffer and restore stdout
-      stdout.flush ();
+      out_stream.flush ();
+      err_stream.flush ();
       retval (0) = buffer.str ();
-      octave_pager_stream::reset ();
+      out_stream.rdbuf (old_out_buf);
+      err_stream.rdbuf (old_err_buf);
+
+      // Reset error state, otherwise this function would
+      // not be able to return anything in case of errors.
+      error_state = 0;
     }
   else
     print_usage ();
````

**Comment by oheim** [comment]
I have found the root of the crashes, please apply the following patch:
````
diff --git a/src/Makefile b/src/Makefile
index 77a3d74..4467b13 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -1,4 +1,4 @@
-MKOCTFILE = mkoctfile -Wall
+MKOCTFILE ?= mkoctfile -Wall
 
 all: doctest_evalc.oct
 
````

You shall not modify the MKOCTFILE if the package is installed from within Octave.

**Comment by oheim** [comment]
I have sent a revised version to the Octave patch tracker (https://savannah.gnu.org/patch/?func=detailitem&item_id=8033). The `error_state = 0;` at the end of the function should be removed for MATLAB compatibility. The capturing of printed error messages would not work within functions anyway.

**Comment by cbm755** [comment]
Thanks!  Just for the record: it previously *did not* work for me on Octave 4 (I didn't report because I figured it was because I was compiling it with Octave 3.8, which might have been the case.).

I've got no problem with giving commit access.  @catch22.

**Comment by cbm755** [comment]
I added some text to the wiki suggesting some [good practice for a workflow](https://github.com/catch22/octave-doctest/wiki/Development-Process).  @catch22 can you check if you're happy and edit if not?   Basically just that major changes are done as PR and when reasonable, we have a +1 before merging.  Not rules, just a target for as this gets more stable.

**Comment by catch22** [comment]
@cbm755 The 'good practices' look good to me. :+1: I have added a small notice that it is possible to send PRs without commit access.

@oheim I'll momentarily merge your evalc fixes. I've also given you push access for future development work. Thanks for all your help.

**Comment by catch22** [comment]
@oheim I have pushed your patch to the `evalc` branch (PR #60). The following line causes errors not to be propagated:

~~~
      // Reset error state, otherwise this function would
      // not be able to return anything in case of errors.
      error_state = 0;
~~~

This behavior appears to differ from Matlab and from our previous evalc 'implementations'. I have therefore commented it out in order not to cause a regression in doctest.
Perhaps you can use your newly-gained commit bits to decide what it is the correct way to fix this :smile:

**Comment by catch22** [comment]
To be clear: I have only applied the patches you posted here, *not* the latest one from the Octave patch tracker.

**Comment by oheim** [comment]
You can drop these three lines. That's what I havemeant with “The `error_state = 0;` at the end of the function should be removed for MATLAB compatibility.“

**Comment by catch22** [comment]
Oh, I must have missed this. How about you pull the just-rebased `evalc` branch & remove them yourself?

**Comment by oheim** [comment]
Done. The oct-file code differs from what is implemented in the Octave patch tracker, but that's not important since doctest does not use multiple output arguments.
