### ISSUE TITLE
doctest_evalc installation

### ISSUE THREAD

**Issue by catch22** [catch22/octave-doctest#63]
Two questions for @oheim and @cbm755:

1. Currently we are invoking `src/Makefile` from the root `Makefile` and add `src` to the Octave path so that `doctest_evalc` is found. Is this the correct way to set up the testing infrastructure? Or should we install the package before running doctests on it? Or is there something like Python's `setup.py develop`?

2. Is it possible to have `doctest_evalc` be installed into `inst/private` rather than `inst` (the latter is the current behavior, right?).

**Comment by oheim** [comment]
1. You can do with or without installation. The solution without the installation is easier and saves a lot of compile time during testing. I can set up the root `Makefile` for a better handling of that case if you wish.
2. No, the package installation routine in Octave core installs the compiled oct-files into an architecture dependent directory (not `inst`), which can only contain public functions.

**Comment by cbm755** [comment]
1. Let's check what "interval" pkg does.

**Comment by cbm755** [comment]
2.  its ok if its public, we'll leave the `doctest_` prefix for now.  Also, this will likely be a temporary solution (I hope).

**Comment by catch22** [comment]
@oheim Please go ahead and make any changes that you deem appropriate (the hardcoded test filenames will be gone after PR #52).

I'll be offline for a little while for a transatlantic flight.

**Comment by oheim** [comment]
I have improved the `Makefile`s a little bit. Since it was only a small change, I have pushed to master directly.

**Comment by catch22** [comment]
Thanks! Is this a typo (or an inconsistency)?
~~~
$(BUILD_DIR) tmp/${MATLAB_PKG_DIR}/private:
~~~

**Comment by oheim** [comment]
The `tmp` could be replaced by $(BUILD_DIR) as well. The rule is for the creation of the two directories.

**Comment by catch22** [comment]
Yeah there are a couple of explicit `tmp` in that file.

**Comment by catch22** [comment]
Do you want to fix that?
