### ISSUE TITLE
Should we provide a fallback for doctest_evalc?

### ISSUE THREAD

**Issue by catch22** [catch22/octave-doctest#65]
The `octave` packages of Debian and Ubuntu do not come with `mkoctfile` and hence are not always installed. Not sure if we should provide the old fake_evalc as a fallback (+ buffering support...).

**Comment by oheim** [comment]
I'd say no. `mkoctfile` is included in the Windows build of Octave, `mkoctfile` can be easily installed with `liboctave-dev` in Debian and if it's missing, the user gets a good hint from Octave:
````
octave:1> pkg install -forge interval
pkg: please install the Debian package "liboctave-dev" to get the mkoctfile command
````

**Comment by cbm755** [comment]
I'd also say no.

OTOH, If you want it around for bit for testing or whatever, I don't mind but definitely not with all the buffering stuff... (just let it interleave).

**Comment by catch22** [comment]
My motivation was that on my local server farm only the `octave` package (but not `liboctave-dev`) is installed. I nevertheless agree, and I think it's good to document these kind of decision and the rationale in the form of github issues. If there are sufficiently many other people suffering from the same problem we might reconsider providing a fallback.

(Note that we also have to use the `octave/stable` PPA for travis, which only provides `octave` but not `liboctave-dev`. For some magic reason, this seems to work with the distributions's `liboctave-dev` package...)
