### ISSUE TITLE
improve white space matching

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#68]
Currently, we collapse all whitespace to single space chars before comparing.  It might be better to:

1.  strtrim each line.  This was, result can be indented arbitrarily.
2.  collapse/ignore blank lines.

Not urgent.  Needs something like #67 for its tests.

Matlab and Octave have different conventions for formatting matrices so this might slightly touch on #35.

**Comment by cbm755** [comment]
Python has `# doctest: +NORMALIZE_WHITESPACE` so this can be controlled on a per-test basic.

**Comment by catch22** [comment]
It's definitely important to keep behavior 1+2 (e.g., I recall that Matlab can introduce spurious newlines in the `evalc` result if the output starts to wrap lines.. so the `evalc` result differs depending on the console width etc.).

I got accustomed to the current behavior of doctest as it allows you to format your test outputs in a nicely human-readable way, even if that is not chosen by Matlab/Octave. Perhaps it would be better to have something like `+STRICT_WHITESPACE`?

**Comment by catch22** [comment]
I guess there is a general question if we need/want to stick as close to Python's doctest as possible.

**Comment by cbm755** [comment]
To be clear, I'm proposing that space within expressions would be strict by default: so these would pass
````
>> sprintf('   a  b     \n           c d')
a  b
c d
````
````
                           a  b
                           c d
````
````

     a  b           




                           c d
````
But this would *fail* as it only has one space between `a` and `b`:
````
a b
c d
````
I'm certainly accustomed both 1. and 2. as well.

But are you relying on custom spacing within lines?  Matrices come to mind...   My brief look in Octave core shows things like
````
1 0
0 1
````
for a matrix which.  So that would fail if we adopt this.

**Comment by cbm755** [comment]
Re terminology and python: we could have `# doctest: -NORMALIZE_WHITESPACE` and `+NORMALIZE_WHITESPACE` be the default.  So same commands as Python but opposite default behavior.

**Comment by catch22** [comment]
Yes, that's how I interpreted your proposal. I felt it was nice to have the freedom of additional whitespace as a default (e.g. when dealing with matrices, though I need to go back and see which examples would break). I like your suggestion on enabling `+NORMALIZE_WHITESPACE` by default (cf. #69).
