### ISSUE TITLE
Python doctest use "..." and we use "***" to match arbitrary text

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#69]
Thoughts on changing to `...` before we get too popular to change? ;-)

`...` looks nice for shortening a long vector output.  Maybe `***` is more natural as "wildcard".

OTOH, from [reading this](https://docs.python.org/3/library/doctest.html#doctest-directives), it looks like you have to enable with:
````
#doctest: +ELLIPSIS
````

**Comment by cbm755** [comment]
["Let's do both"](http://dilbert.com/strip/1996-01-27) ?

**Comment by catch22** [comment]
Hmm, I've no strong opinion really, though I feel that `***` sticks out nicely.

Does Matlab/Octave ever truncate vectors when displaying them? If yes, which character does it use? (If it uses `...` then we should use something differently.)

**Comment by cbm755** [comment]
Hmmm, not that I know of.  Maybe this is why `+ELLIPSIS` is not default in Python.

Shall we just ignore this?  We can always add `...` later if there is demand.

**Comment by catch22** [comment]
That sounds good to me.

**Comment by catch22** [comment]
On the other hand, given #68 it would be nicely symmetric if we indeed used `...` and enabled `+ELLIPSIS` by default. I will check out if there are any issues in my codebase that uses doctest.

**Comment by catch22** [comment]
I think we should decide for either `...` or `***`, but not both. I checked my codebase and did not find any obvious problems with using the former. As you prefer to stick with doctest conventions, I think I vote for `...` (but to have `+ELLIPSIS` as a default). I'll prepare a PR.

**Comment by catch22** [comment]
See PR #77.

**Comment by cbm755** [comment]
Great!  I think that is the right decision: first-and-foremost tests should be readable and `...` is better for that.
