### ISSUE TITLE
Allow default directives

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#74]
Eventually it would be nice to specify the `NORMALIZEWHITESPACE` default on the command line.

E.g.,
`doctest . -recurse -NORMALIZEWHITESPACE`

or
`doctest . -recurse +NORMALIZEWHITESPACE`

(Not necessary for 0.4.0.)

**Comment by catch22** [comment]
OTOH, it would be good if the semantics of a doctest was obvious from the doctest alone. What would be the use case for this feature?

**Comment by cbm755** [comment]
Its so that *projects* can run with stricter whitespace if they choose.  I just ran the Symbolic package with strict mode and fixed a couple minor things (https://github.com/cbm755/octsympy/commit/b49b27c4d7cf0f3545ecee0b2d5864394241c97d).

**Comment by catch22** [comment]
Ah, I understand. :+1:
