### ISSUE TITLE
fopen warning

### ISSUE THREAD

**Issue by catch22** [catch22/octave-doctest#79]
I get `warning: fopen: file found in load path` since a little while. Is this because of the `.texinfo` files that get `fopen`ed from the path?

(I think this might get auto-fixed as we add support for test collection in directories...)

**Comment by cbm755** [comment]
confirmed

**Comment by cbm755** [comment]
#85 fixes this, as we don't rely on finding stuff we're testing in the path but rather chdir.

**Comment by cbm755** [comment]
should be fixed
