### ISSUE TITLE
new recursive code mishaves on Symbolic's @logical dir

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#86]
[On top of #85.]

`doctest logical` does not work properly.

**Comment by cbm755** [comment]
Its because `logical` is a builtin as well as a `@logical` class...

**Comment by cbm755** [comment]
lack of `exist(foo, 'class')` on octave is aggravating.

**Comment by catch22** [comment]
I wonder if it makes sense to separate out our `exists` escapades into a separate function...
