### ISSUE TITLE
Recursive collects non-source files

### ISSUE THREAD

**Issue by catch22** [catch22/octave-doctest#94]
E.g., `doctest . -recursive` enters `.git` (which is perhaps fine, although we might want to skip dotdirs?) and attempts to test all sort of files (which is not so fine :smile:).

**Comment by cbm755** [comment]
presumably even without recursion it tests all sorts of files in `.` (?)

+1 for skipping dotdirs.

**Comment by catch22** [comment]
I think that's right (probably `.git` was just the first directory entry).
