### ISSUE TITLE
Recursive option syntax

### ISSUE THREAD

**Issue by catch22** [catch22/octave-doctest#95]
How about we use `+recursive` / `-recursive` just as for the other directives? Hmm.

**Comment by cbm755** [comment]
Yes I had also thought this might be a good idea (although its a bit non-standard from a command line options point-of-view).

I don't think I feel strongly either way.

**Comment by catch22** [comment]
Hmm, the other alternative would be to change the `doctest` directives argument to something like
~~~
-directives '+FOO -BAR'
~~~
but this is also kind of unwieldy (?).

What do you think @oheim?

**Comment by oheim** [comment]
The standard way (if there is any–in octave I know this behaviour only from the `pkg` command) would be to have all options passed as `-option` and have different identifiers for opposite behaviours, i. e., `-recursive` and `-nonrecursive`.

**Comment by catch22** [comment]
Yeah; right now, this clashes with our use of `+FOO -BAR` for directives (the same syntax which is also used in individual doctests).

**Comment by cbm755** [comment]
I still don't feel so strongly about it.  But I'm thinking just go for `-recursive/-nonrecursive` and `+DIRECTIVE/-DIRECTIVE`.  And hope that the CAPS somehow defuse the palpable tension :)

**Comment by cbm755** [comment]
I can do a PR adding `-nonrecursive`.  But an API change flipping meaning of `-recursive` ain't gonna happen on a point release...

**Comment by catch22** [comment]
I think `-recursive` is fine (but how about #127 instead? :)

**Comment by cbm755** [comment]
In the post-cmdline-directive world, we could make recursive the default... (and have a `-nonrecursive` option).  Is this doing the right thing by default?

**Comment by catch22** [comment]
My test runner of choice in the Python world (`pytest`) defaults to recursion and it always seemed like a useful default to me. If this doesn't bother you it would be wonderful to change the default to recursion and add a `-nonrecursive` option.

I'm not sure how to gracefully deprecate the behavior before changing it (except for printing an annoying deprecation message throughout the next major version), but it might be fine to just change this for 0.5 if we decide to go down that route, since it will in the worst case only lead to more tests being run! :smile:

**Comment by cbm755** [comment]
All sound good to me.

**Comment by catch22** [comment]
I'll go ahead and create a PR for that change.

By the way, has there been any recent discussion on Octave's mailing list with regards to using doctests in the octave-core?

**Comment by cbm755** [comment]
I can do it in #118.

I haven't seen any further discussion, suspect we'd need to push (and may need to fix up #119 to only do that on texinfo...)

**Comment by catch22** [comment]
Thanks!

**Comment by cbm755** [comment]
This is fixed by #118.
