### ISSUE TITLE
Spit long rows

### ISSUE THREAD

**Issue by catch22** [catch22/octave-doctest#96]
What do you guys think about calling `split_long_rows` in the test driver (with the `local` option)? This should make doctests more reproducible and it complements nicely the "whitespace compression" feature.

**Comment by cbm755** [comment]
I didn't know about this.  Sounds like a good idea to me.

Longer term: ideally one could call that with an optional value of chars, overriding the terminal width.  Then we could decide on a value (e.g., 72 chars? some PEP has a suggested width for docstrings) and the test results would no longer depend on the current physical terminal width...  But this would require upstream Octave changes.

**Comment by catch22** [comment]
I feel that it might be more intuitive to switch off the option completely (in which case the test results will also not depend on the current physical terminal width).

My reasoning is the following: At least in my case, doctests typically arise either from (1) me typing the expected result in the text editor (TDD-style) or (2) from copy & pasting code from the Octave prompt. 
In the first case, it's a bit cumbersome if one has to manually imitate the column splitting behavior by hand, while in the second case the width of the physical terminal being used is usually >> 72 and so no wrapping will occur for sane test cases; this would again lead to manual action.

PS: I don't know how to programmatically change the output width in Matlab.

**Comment by cbm755** [comment]
> I feel that it might be more intuitive to switch off the option
> completely (in which case the test results will also not depend on
> the current physical terminal width).

Yes, maybe.  E.g., I've recently had my CI fail on another because 
Travis CI ran with a narrower (virtual) terminal.

**Comment by catch22** [comment]
Yeah, I had the same experience (even between interactive doctest runs from the Octave prompt vs. non-interactive runs from `make test`).
