### ISSUE TITLE
reformat doc as texinfo

### ISSUE THREAD

**Issue by cbm755** [catch22/octave-doctest#98]
pros:
- looks better on octave-forge e.g., [here](http://octave.sourceforge.net/doctest/function/doctest.html)
- will need it anyway for a merge to octave-core

cons:
- package also tests plain m-files without mark-up and the documentation of doctest.m is a nice example of such.

todo
- [x] reformat doc as texinfo
- [x] generate plain text in "make matlab_pkg".

**Comment by catch22** [comment]
Despite disliking texinfo, I fear you are completely correct :smile: 

Also, I don't think it's strictly necessary to worry about generating plain text for Matlab.

**Comment by cbm755** [comment]
heh :)

Its easy enough to get plain text out of it (do this in Symbolic pkg), but will need to see if satisfies two-blank-lines-after-example rule...

**Comment by cbm755** [comment]
Started this in #101.

**Comment by catch22** [comment]
I merged #101. Did you still want to generate some sort of Matlab output?

**Comment by cbm755** [comment]
See PR #114

**Comment by cbm755** [comment]
And closing
