### ISSUE TITLE
Hide doctest_evalc from autogenerated documentation

### ISSUE THREAD

**Issue by catch22** [catch22/octave-doctest#99]
It's a bit confusing that `doctest_evalc` is currently displayed on http://octave.sourceforge.net/doctest/overview.html. If there is no good way to fix this, let us at least rename `doctest_eval` to something like `__doctest_evalc`.

**Comment by oheim** [comment]
There is a good way to fix it. You can create an [INDEX file](https://www.gnu.org/software/octave/doc/interpreter/The-INDEX-File.html#The-INDEX-File) and only add the `doctest` function to it.

**Comment by catch22** [comment]
Done per a5239b1f6eebeab36a6afe004ec6efbce6a9cad5 (have a look?)
